# installing lamp stack with ansible
---
- hosts: all
  become: yes
  tasks:
  - name: update packages & install apache2 
    apt: 
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache
    when: ansible_os_family == "Debian"
  - name: install httpd
    yum:
      name: httpd
      state: present
      enabled: yes
    when: ansible_os_family == "RedHat"  
  - name: install php packages
    apt: 
      name: "{{ item }}"
      state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql
    notify:
    - restart apache2
    when: ansible_os_family == "Debian"
  - name: install php for redhat
    yum:
      name: {{ item }} 
      state: present
    with_items:
      - php
      - php-mysql
    notify: restart httpd
    when: ansible_os_family == "RedHat"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
  - name: restart httpd
    service:
      name: httpd
      enabled: yes
      state: restarted
    when: ansible_os_family == "RedHat"

