# installing lamp stack with ansible
---
- hosts: all
  become: yes
  tasks:
  - name: update packages & install apache2 
    apt: 
      name: apache2
      update_cache: yes
      state: present
    notify:
    - restart apache
    when: ansible_os_family == "Debian" 
  - name: install php packages
    apt: 
      name: "{{ item }}"
      state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mcrypt
        - php-mysql
    notify:
    - restart apache2
    when: ansible_os_family == "Debian"
  handlers:
  - name: restart apache
    service:
      name: apache2
      enabled: yes
      state: restarted
    when: ansible_os_family == "Debian"
