# ansible -m ping all
---
- hosts: all
  become: yes
  tasks: 
  - name: Execute ansible ping on hosts
    ping: 
  - name: update ubuntu pachakags
    apt:
      update_cache: yes
      state: present
  - name: install tree
    apt:
      name: tree
      state: present